In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
dataset= pd.read_excel('/content/drive/My Drive/Colab Notebooks/Dataset/DATASET education.xlsx')
dataset

10th  12th  B.Tech  7-SEM  6-SEM  5-SEM  Final Performance  Medium  \
0    74.83  75.2   72.80  67.04  34.53  18.40              56.77       2   
1    89.30  80.8   69.60  73.49  31.81  21.50              61.38       1   
2    79.83  75.4   58.70  62.82  31.44   5.38              51.81       2   
3    68.40  59.6   54.40  65.17  35.92  10.92              54.84       1   
4    79.80  69.8   74.45  76.24  44.50  44.20              67.80       1   
..     ...   ...     ...    ...    ...    ...                ...     ...   
114  76.00  82.6   68.25  56.96  22.25   7.50              46.25       1   
115  83.60  75.8   70.10  64.83  34.22   7.08              53.92       1   
116  89.30  68.4   77.55  67.57  36.82  25.64              58.27       1   
117  89.30  72.0   74.90  65.10  31.44  35.75              56.63       1   
118  53.20  71.6   71.00  40.08  30.53   0.88              34.48       1   

      Package  Placed  
0      5.0LPA       1  
1        0LPA       0  
2        0LPA       0  
3     10.0LPA       1  
4    3.36 LPA       1  
..        ...     ...  
114   3.8 LPA       1  
115   3.6 LPA       1  
116   3.8 LPA       1  
117      0LPA       0  
118  2.40 LPA       1  

[119 rows x 10 columns]

In [ ]:
dataset.isnull().sum()

10th                 0
12th                 0
B.Tech               0
7-SEM                0
6-SEM                0
5-SEM                0
Final Performance    0
Medium               0
Package              0
Placed               0
dtype: int64

In [ ]:
#Count total number of classes in Data
class_counts = dataset.groupby('Placed').size()
print(class_counts)

Placed
0    36
1    83
dtype: int64


In [ ]:
dataset.describe()

10th        12th      B.Tech       7-SEM       6-SEM       5-SEM  \
count  119.000000  119.000000  119.000000  119.000000  119.000000  119.000000   
mean    78.908235   72.000000   66.523109   62.792773   37.074202   26.036975   
std      9.670518    9.984938    9.915475   11.930053    9.680815   17.317577   
min     53.200000   49.000000   26.850000    2.130000    3.240000    0.000000   
25%     72.200000   64.900000   61.325000   56.980000   32.265000   11.835000   
50%     79.800000   71.600000   68.350000   63.260000   37.840000   24.150000   
75%     85.500000   80.100000   72.875000   68.900000   43.090000   35.515000   
max     96.830000   92.200000   85.950000   94.000000   59.410000   80.400000   

       Final Performance      Medium      Placed  
count         119.000000  119.000000  119.000000  
mean           53.690672    1.226891    0.697479  
std            11.413422    0.420592    0.461292  
min             1.230000    1.000000    0.000000  
25%            48.535000    1.000000    0.000000  
50%            54.080000    1.000000    1.000000  
75%            59.440000    1.000000    1.000000  
max            76.030000    2.000000    1.000000

In [ ]:
X  = dataset.iloc[:,0:8]
y = dataset.iloc[:, 9]

In [ ]:
print(X)

      10th  12th  B.Tech  7-SEM  6-SEM  5-SEM  Final Performance  Medium
0    74.83  75.2   72.80  67.04  34.53  18.40              56.77       2
1    89.30  80.8   69.60  73.49  31.81  21.50              61.38       1
2    79.83  75.4   58.70  62.82  31.44   5.38              51.81       2
3    68.40  59.6   54.40  65.17  35.92  10.92              54.84       1
4    79.80  69.8   74.45  76.24  44.50  44.20              67.80       1
..     ...   ...     ...    ...    ...    ...                ...     ...
114  76.00  82.6   68.25  56.96  22.25   7.50              46.25       1
115  83.60  75.8   70.10  64.83  34.22   7.08              53.92       1
116  89.30  68.4   77.55  67.57  36.82  25.64              58.27       1
117  89.30  72.0   74.90  65.10  31.44  35.75              56.63       1
118  53.20  71.6   71.00  40.08  30.53   0.88              34.48       1

[119 rows x 8 columns]


In [ ]:
print(y)

0      1
1      0
2      0
3      1
4      1
      ..
114    1
115    1
116    1
117    0
118    1
Name: Placed, Length: 119, dtype: int64


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 5)

In [ ]:
X_train

10th  12th  B.Tech  7-SEM  6-SEM  5-SEM  Final Performance  Medium
60   95.00  68.6   70.50  66.25  19.54  12.59              53.16       1
22   70.00  64.4   55.30  59.42  32.04  28.04              51.76       2
64   85.50  82.2   79.70  72.86  45.93  30.03              64.08       1
110  76.00  84.2   68.45  59.87  41.15  24.15              53.16       1
70   70.00  61.8   66.75  63.80  40.29  40.73              57.62       1
..     ...   ...     ...    ...    ...    ...                ...     ...
102  68.40  54.4   26.85  63.89  17.47  29.97              52.88       1
61   53.20  53.6   59.75  45.33  41.45  43.15              44.48       1
111  76.67  69.2   65.00  60.97  27.75  34.88              52.91       2
78   73.83  80.2   59.70  57.35  41.53  10.64              49.97       2
99   86.33  89.8   70.85  62.65  34.00  31.91              54.85       2

[89 rows x 8 columns]

In [ ]:
y_train

60     1
22     0
64     1
110    1
70     0
      ..
102    0
61     1
111    1
78     0
99     1
Name: Placed, Length: 89, dtype: int64

In [ ]:
X_test

10th  12th  B.Tech  7-SEM  6-SEM  5-SEM  Final Performance  Medium
71   77.90  58.4   61.45  72.48  45.71  21.76              62.91       1
59   73.17  68.8   71.60  62.29  34.38   6.01              51.96       1
39   87.40  79.6   69.90  65.89  39.65  37.28              58.70       1
10   81.70  61.4   68.15  61.32  44.05  37.44              56.06       1
83   70.30  58.4   68.35  49.24  38.52   7.11              43.15       1
23   74.10  66.6   57.35  42.18  11.14  13.90              34.24       1
57   70.30  58.8   55.70  63.24  36.07   9.03              53.25       1
42   72.20  53.2   55.00  60.89  35.58  16.36              52.20       1
56   80.50  89.2   80.65  63.26  39.16  42.79              57.25       2
74   62.70  62.8   67.20  55.67  41.23   4.68              48.07       1
28   74.10  65.6   64.55  58.82  29.48   4.76              48.49       1
35   95.00  89.0   77.05  65.71  37.84  41.38              58.70       1
17   66.50  75.2   74.55  73.76  46.46  37.97              65.65       1
79   74.10  64.8   59.35  65.00  39.12  16.70              55.83       1
63   67.17  86.6   64.60  46.34  40.66  39.60              44.73       2
6    77.33  65.6   66.30  73.34  49.02  23.09              64.22       1
114  76.00  82.6   68.25  56.96  22.25   7.50              46.25       1
91   86.83  78.4   72.05  66.16  43.41  31.86              58.94       2
98   89.33  82.4   80.90  71.68  44.65   6.56              60.58       1
88   95.00  82.4   77.60  63.83  44.39  15.82              55.73       1
20   81.70  56.8   59.90  59.94  41.60  22.47              53.11       1
49   82.33  83.2   77.05  61.69  45.22  47.15              57.52       2
43   72.20  63.2   48.20  54.38  32.15   6.99              45.90       1
66   92.67  86.0   73.15  71.63  46.01  25.76              62.75       1
37   81.00  84.8   68.95  62.63  41.45  40.76              56.95       2
48   72.20  60.8   60.85  68.27  32.83  15.31              57.07       1
97   83.83  80.0   69.00  73.46  36.48  28.40              62.83       2
116  89.30  68.4   77.55  67.57  36.82  25.64              58.27       1
81   81.70  59.2   68.00  67.86  40.70  17.64              58.29       1
46   76.00  74.6   63.05  81.49  27.86  52.32              69.82       1

In [ ]:
y_test

71     1
59     1
39     1
10     1
83     1
23     1
57     0
42     0
56     1
74     1
28     0
35     1
17     1
79     1
63     1
6      1
114    1
91     1
98     1
88     1
20     0
49     1
43     0
66     1
37     1
48     0
97     1
116    1
81     1
46     1
Name: Placed, dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform (X_test)
print(np.mean(X_train))
print(np.std(X_train))

2.650813401492649e-16
1.0


# Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(random_state=42).fit(X_train, y_train)
y_pred = log_reg.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[ 5  1]
 [ 2 22]]


In [ ]:
from sklearn.metrics import accuracy_score
print('Accuracy: %.3f' % (accuracy_score(y_test, y_pred)*100))
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
precision = precision_score(y_test, y_pred, average='binary')
print('Precision: %.3f' % (precision*100))
recall = recall_score(y_test, y_pred, average='binary')
print('Recall: %.3f' % (recall*100))
score = f1_score(y_test, y_pred, average='binary')
print('F-Measure: %.3f' % (score*100))

Accuracy: 90.000
Precision: 95.652
Recall: 91.667
F-Measure: 93.617


In [ ]:
score = log_reg.score(X_test, y_test)
print(score)

0.9


In [ ]:
Tenth = 63.5 #@param {type:"number"}
Twelth = 59.6 #@param {type:"number"}
BTech = 59.9 #@param {type:"number"}
SeventhSEM	= 50.74 #@param {type:"number"}
SixthSEM = 36.22 #@param {type:"number"}
FifthSEM = 4.94 #@param {type:"number"}
Final = 43.66 #@param {type:"number"}
Medium =  1#@param {type:"number"}
output=log_reg.predict(sc.transform([[Tenth,Twelth,BTech,SeventhSEM,SixthSEM,FifthSEM,Final,Medium]]))
print("Purchased =", output)
if output==[1]:
  print( 'Student is Placed')
else:
  print('Student is not Placed')

Purchased = [0]
Student is not Placed


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
import pickle 
print("[INFO] Saving model...")
saved_model0=pickle.dump(log_reg,open('/content/drive/My Drive/Colab Notebooks/Logistic-modelproject-6.pkl', 'wb'))

[INFO] Saving model...


In [ ]:
model0 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/Logistic-modelproject-6.pkl','rb'))
model0.predict(X_test)

array([1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1])

# Naive Bayes Algorithm

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
y_pred

array([1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[ 6  0]
 [ 5 19]]


In [ ]:
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
precision = precision_score(y_test, y_pred, average='binary')
print('Precision: %.3f' % (precision*100))
from sklearn.metrics import f1_score
score = f1_score(y_test, y_pred, average='binary')
print('F-Measure: %.3f' % (score*100))
recall = recall_score(y_test, y_pred, average='binary')
print('Recall: %.3f' % (recall*100))

Accuracy: 83.33
Precision: 100.000
F-Measure: 88.372
Recall: 79.167


In [ ]:
Tenth = 63.5 #@param {type:"number"}
Twelth = 59.6 #@param {type:"number"}
BTech = 59.9 #@param {type:"number"}
SeventhSEM	= 50.74 #@param {type:"number"}
SixthSEM = 36.22 #@param {type:"number"}
FifthSEM = 4.94 #@param {type:"number"}
Final = 43.66 #@param {type:"number"}
Medium =  1#@param {type:"number"}
output=classifier.predict(sc.transform([[Tenth,Twelth,BTech,SeventhSEM,SixthSEM,FifthSEM,Final,Medium]]))
print("Purchased =", output)
if output==[1]:
  print( 'Student is Placed')
else:
  print('Student is not Placed')

Purchased = [0]
Student is not Placed


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
import pickle 
print("[INFO] Saving model...")
saved_model1=pickle.dump(classifier,open('/content/drive/My Drive/Colab Notebooks/Naive_Bayes-modelproject-6.pkl', 'wb'))

[INFO] Saving model...


In [ ]:
model1 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/Naive_Bayes-modelproject-6.pkl','rb'))
model1.predict(X_test)

array([1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1])

# SVM Algorithm

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 5, probability=True)
classifier.fit(X_train, y_train)

SVC(probability=True, random_state=5)

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
y_pred

array([1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[ 6  0]
 [ 4 20]]


In [ ]:
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
precision = precision_score(y_test, y_pred, average='binary')
print('Precision: %.2f' % (precision*100))
recall = recall_score(y_test, y_pred, average='binary')
print('Recall: %.3f' % (recall*100))
score = f1_score(y_test, y_pred, average='binary')
print('F-Measure: %.3f' % (score*100))

Accuracy: 86.67
Precision: 100.00
Recall: 83.333
F-Measure: 90.909


In [ ]:
Tenth = 77.90 #@param {type:"number"}
Twelth = 58.4 #@param {type:"number"}
BTech = 61.45 #@param {type:"number"}
SeventhSEM	= 72.48 #@param {type:"number"}
SixthSEM = 45.71 #@param {type:"number"}
FifthSEM = 21.76 #@param {type:"number"}
Final = 62.91 #@param {type:"number"}
Medium =  1#@param {type:"number"}
output=classifier.predict(sc.transform([[Tenth,Twelth,BTech,SeventhSEM,SixthSEM,FifthSEM,Final,Medium]]))
print("Purchased =", output)
if output==[1]:
  print( 'Student is Placed')
else:
  print('Student is not Placed')

Purchased = [1]
Student is Placed


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
import pickle 
print("[INFO] Saving model...")
saved_model2=pickle.dump(classifier,open('/content/drive/My Drive/Colab Notebooks/SVM-modelproject-6.pkl', 'wb'))

[INFO] Saving model...


In [ ]:
model2 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/SVM-modelproject-6.pkl','rb'))
model2.predict(X_test)

array([1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1])

# Random Forest Algorithm

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier_Random = RandomForestClassifier(n_estimators = 300, criterion = 'entropy', random_state = 5)
classifier_Random.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=300, random_state=5)

In [ ]:
y_pred = classifier_Random.predict(X_test)

In [ ]:
y_pred

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[ 6  0]
 [ 5 19]]


In [ ]:
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
precision = precision_score(y_test, y_pred, average='binary')
print('Precision: %.2f' % (precision*100))
recall = recall_score(y_test, y_pred, average='binary')
print('Recall: %.3f' % (recall*100))
score = f1_score(y_test, y_pred, average='binary')
print('F-Measure: %.3f' % (score*100))

Accuracy: 83.33
Precision: 100.00
Recall: 79.167
F-Measure: 88.372


In [ ]:
Tenth = 77.90 #@param {type:"number"}
Twelth = 58.4 #@param {type:"number"}
BTech = 61.45 #@param {type:"number"}
SeventhSEM	= 72.48 #@param {type:"number"}
SixthSEM = 45.71 #@param {type:"number"}
FifthSEM = 21.76 #@param {type:"number"}
Final = 62.91 #@param {type:"number"}
Medium =  1#@param {type:"number"}
output=classifier_Random.predict(sc.transform([[Tenth,Twelth,BTech,SeventhSEM,SixthSEM,FifthSEM,Final,Medium]]))
print("Purchased =", output)
if output==[1]:
  print( 'Student is Placed')
else:
  print('Student is not Placed')

Purchased = [0]
Student is not Placed


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
import pickle 
print("[INFO] Saving model...")
saved_model3=pickle.dump(classifier_Random,open('/content/drive/My Drive/Colab Notebooks/Random_Forest-modelproject-6.pkl', 'wb'))

[INFO] Saving model...


In [ ]:
model3 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/Random_Forest-modelproject-6.pkl','rb'))
model3.predict(X_test)

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1])

# Decision Tree Algorithm

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 5)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=5)

In [ ]:
y_pred = classifier.predict(X_test)
y_pred

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[ 2  4]
 [ 3 21]]


In [ ]:
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
precision = precision_score(y_test, y_pred, average='binary')
print('Precision: %.2f' % (precision*100))
recall = recall_score(y_test, y_pred, average='binary')
print('Recall: %.3f' % (recall*100))
score = f1_score(y_test, y_pred, average='binary')
print('F-Measure: %.3f' % (score*100))

Accuracy: 76.67
Precision: 84.00
Recall: 87.500
F-Measure: 85.714


In [ ]:
Tenth = 77.90 #@param {type:"number"}
Twelth = 58.4 #@param {type:"number"}
BTech = 61.45 #@param {type:"number"}
SeventhSEM	= 72.48 #@param {type:"number"}
SixthSEM = 45.71 #@param {type:"number"}
FifthSEM = 21.76 #@param {type:"number"}
Final = 62.91 #@param {type:"number"}
Medium =  1#@param {type:"number"}
output=classifier.predict(sc.transform([[Tenth,Twelth,BTech,SeventhSEM,SixthSEM,FifthSEM,Final,Medium]]))
print("Purchased =", output)
if output==[1]:
  print( 'Student is Placed')
else:
  print('Student is not Placed')

Purchased = [1]
Student is Placed


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
import pickle 
print("[INFO] Saving model...")
saved_model4=pickle.dump(classifier,open('/content/drive/My Drive/Colab Notebooks/Decision_Tree-modelproject-6.pkl', 'wb'))

[INFO] Saving model...


In [ ]:
model4 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/Decision_Tree-modelproject-6.pkl','rb'))
model4.predict(X_test)

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1])

# KNN Algorithm

In [ ]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier =  KNeighborsClassifier(n_neighbors = 15, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=15)

In [ ]:
y_pred = classifier.predict(X_test)
y_pred

array([1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[ 4  2]
 [ 2 22]]


In [ ]:
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
precision = precision_score(y_test, y_pred, average='binary')
print('Precision: %.2f' % (precision*100))
recall = recall_score(y_test, y_pred, average='binary')
print('Recall: %.3f' % (recall*100))
score = f1_score(y_test, y_pred, average='binary')
print('F-Measure: %.3f' % (score*100))

Accuracy: 86.67
Precision: 91.67
Recall: 91.667
F-Measure: 91.667


In [ ]:
Tenth = 77.90 #@param {type:"number"}
Twelth = 58.4 #@param {type:"number"}
BTech = 61.45 #@param {type:"number"}
SeventhSEM	= 72.48 #@param {type:"number"}
SixthSEM = 45.71 #@param {type:"number"}
FifthSEM = 21.76 #@param {type:"number"}
Final = 62.91 #@param {type:"number"}
Medium =  1#@param {type:"number"}
output=classifier.predict(sc.transform([[Tenth,Twelth,BTech,SeventhSEM,SixthSEM,FifthSEM,Final,Medium]]))
print("Purchased =", output)
if output==[1]:
  print( 'Student is Placed')
else:
  print('Student is not Placed')

Purchased = [1]
Student is Placed


In [ ]:
import pickle 
print("[INFO] Saving model...")
saved_model5=pickle.dump(classifier,open('/content/drive/My Drive/Colab Notebooks/KNN-modelproject-6.pkl', 'wb'))

[INFO] Saving model...


In [ ]:
model5 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/KNN-modelproject-6.pkl','rb'))
model5.predict(X_test)

array([1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1])

In [ ]:
%mkdir templates -p

In [ ]:
%%writefile templates/index.html
<!DOCTYPE html>
<html >
<!--From https://codepen.io/frytyler/pen/EGdtg-->
<head>
<title>Machine Learning KNN Deployment</title>
<meta charset="UTF-8">
<link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous"> 
<style><!DOCTYPE html>

h1 {text-align: center;}
h2 {text-align: center;}
h3 {text-align: center;}
p {text-align: center;}
div {text-align: center;}
</style>

<style>
.myDiv {
  border: 10px outset lightblue;
  background-color: lightblue;    
  text-align: center;
}

.button {
  background-color: lightblue;
  border: none;
  color: white;
  padding: 16px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  transition-duration: 0.4s;
  cursor: pointer;

}
.button1 {
  background-color: white; 
  color: black; 
  border: 5px solid darkblue;
}

.button1:hover {
  background-color: #f64949ab;
  color: white;
}

.button2 {
  background-color: white; 
  color: black; 
  border: 5px solid darkblue;
}

.button2:hover {
  background-color: #37bea5;
  color: white;
}

.button3 {
  background-color: white; 
  color: black; 
  border: 5px solid darkblue;
}

.button3:hover {
  background-color: #9c0e9d;
  color: white;
}

.button4 {
  background-color: white; 
  color: black; 
  border: 5px solid darkblue;
}

.button4:hover {
  background-color: #b1c711;
  color: white;
}

.button5 {
  background-color: white; 
  color: black; 
  border: 5px solid darkblue;
}

.button5:hover {
  background-color: #740821;
  color: white;
}

.button6 {
  background-color: white; 
  color: black; 
  border: 5px solid darkblue;
}

.button6:hover {
  background-color: #0eab60;
  color: white;
}
</style>
</head>

<body>
      
<div class="myDiv" style="background-color:grey;" >
           
<div class="col-md-12">
<center><p style="font-size:40px;color:white;margin-top:10px;">Poornima Institute of Engineering & Technology</p></center> 
<center><p style="font-size:30px;color:white;margin-top:10px;">Department of Computer Engineering</p></center> 
<center><p style="font-size:25px;color:white;margin-top:10px;">Summer Internship 2022 on Machine learning and Data Science</p></center> 
</div>

<div class="login">
<h2 ><u>Analysis to Predict If a Student Is Placed Or Not</u></h2>
<h3><i><u>Developed by Alok Raj</i></u></h3>
<!-- Main Input For Receiving Query to our ML -->
<form action="{{ url_for('predict')}}"method="get">


<div class="form-floating mb-3">

<input type="number" class="form-control" id="10th" name="10th" step="any" min="0.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter 10th Marks</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="12th" name="12th" step="any" min="0.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter 12th Marks</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="B.Tech" name="B.Tech" step="any" min="0.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter B.Tech Marks</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="7-SEM" name="7-SEM" step="any" min="0.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter 7-SEM Marks</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="6-SEM" name="6-SEM" step="any" min="0.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter 6-SEM Marks</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="5-SEM" name="5-SEM" step="any" min="0.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter 5-SEM Marks</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="Final Performance" name="Final Performance" step="any" min="0.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter Final Performance Marks</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="Medium" name="Medium" step="any" min="1" max="2" placeholder="0" required="required">
<label for="floatingInput">Enter Medium</label>
</div>
<br>

<br>
 <div class="col-md-4" style="color: #FFF;">
                <label for="inputState" class="form-label">Choose a Model</label>
                <select id="Model" name ="Model" step = "any" class="form-select" required>
                    <option selected>Logistic Prediction</option>
                    <option>Naive Bayes Prediction</option>
                    <option>SVM Prediction</option>
                    <option>Random Forest Prediction</option>
                    <option>Decision Tree Prediction</option>
                    <option>KNN Prediction</option>
                </select>
            </div>
            <br>
            <div class="col-12">
                <button type="submit" value="NB" name="NB" class="btn btn-outline-danger">Submit</button>
            </div>
</form>
<br>
<br>

<div class="myDiv">
<h2>
{{ prediction_text }}
</h2>
</div>

</div>

<div class="" style="background-color:green;" >
<div class="clearfix">
           
<div class="col-md-12">
 <center><p style="font-size:25px;color:white;margin-top:20px;border: 10px outset #37b486;">Experiment Performed in Summer internship 2022 from 27 June to 8 August </p></center> 
</div>

</div>
</div>
</body>
</html>

Overwriting templates/index.html


In [ ]:
!pip install flask-ngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install pyngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!ngrok authtoken 2CT4MHWPe5W1c3i8WbPIkMfV3YB_7M1jKwhLC4HVFvS11Rbf

Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml


In [ ]:
import numpy as np
from flask import Flask, request, jsonify, render_template
from flask_ngrok import run_with_ngrok
import pickle


app = Flask(__name__)
model0 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/Logistic-modelproject-6.pkl','rb'))
model1 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/Naive_Bayes-modelproject-6.pkl','rb'))
model2 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/SVM-modelproject-6.pkl','rb'))
model3 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/Random_Forest-modelproject-6.pkl','rb'))
model4 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/Decision_Tree-modelproject-6.pkl','rb'))
model5 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/KNN-modelproject-6.pkl','rb'))
run_with_ngrok(app)

@app.route('/')
def home():
  
    return render_template("index.html")
  
@app.route('/predict',methods=['GET'])

def predict():
    
    Tenth = float(request.args.get('10th'))
    Twelth = float(request.args.get('12th'))
    BTech = float(request.args.get('B.Tech'))
    SeventhSEM = float(request.args.get('7-SEM'))
    SixthSEM = float(request.args.get('6-SEM'))
    FifthSEM = float(request.args.get('5-SEM'))
    FinalPerformance = float(request.args.get('Final Performance'))
    Medium = int(request.args.get('Medium'))

# CreditScore	Geography	Gender	Age	Tenure	Balance	NumOfProducts	HasCrCard	IsActiveMember	EstimatedSalary
    Model = str(request.args.get('Model'))

    if Model=='Logistic Prediction':
      prediction = model0.predict([[Tenth,Twelth,BTech,SeventhSEM,SixthSEM,FifthSEM,FinalPerformance,Medium]])
    
    elif Model=='Naive Bayes Prediction':
      prediction = model1.predict([[Tenth,Twelth,BTech,SeventhSEM,SixthSEM,FifthSEM,FinalPerformance,Medium]])
    
    elif Model=='SVM Prediction':
      prediction = model2.predict([[Tenth,Twelth,BTech,SeventhSEM,SixthSEM,FifthSEM,FinalPerformance,Medium]])

    elif Model=='Random Forest Prediction':
      prediction = model3.predict([[Tenth,Twelth,BTech,SeventhSEM,SixthSEM,FifthSEM,FinalPerformance,Medium]])

    elif Model=='Decision Tree Prediction':
      prediction = model4.predict([[Tenth,Twelth,BTech,SeventhSEM,SixthSEM,FifthSEM,FinalPerformance,Medium]])
    
    else:
      prediction = model5.predict([[Tenth,Twelth,BTech,SeventhSEM,SixthSEM,FifthSEM,FinalPerformance,Medium]])

    
    if prediction == [1]:
      text = "Student is Placed"
    else:
      text = "Student is not Placed"

    return render_template('index.html', prediction_text='Logistic Regression Algorithm Prediction: {}'.format(text))

app.run()


 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)


 * Running on http://2581-34-86-48-236.ngrok.io
 * Traffic stats available on http://127.0.0.1:4040


INFO:werkzeug:127.0.0.1 - - [10/Aug/2022 06:34:35] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Aug/2022 06:34:40] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [10/Aug/2022 06:36:44] "GET /predict?10th=63.5&12th=59.6&B.Tech=59.9&7-SEM=50.74&6-SEM=36.22&5-SEM=4.94&Final+Performance=43.66&Medium=1&Model=Naive+Bayes+Prediction&NB=NB HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Aug/2022 06:37:12] "GET /predict?10th=63.5&12th=59.6&B.Tech=59.9&7-SEM=50.74&6-SEM=36.22&5-SEM=4.94&Final+Performance=43.66&Medium=1&Model=Logistic+Prediction&NB=NB HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Aug/2022 06:39:05] "GET /predict?10th=63.5&12th=59.6&B.Tech=59.9&7-SEM=50.74&6-SEM=36.22&5-SEM=4.94&Final+Performance=43.66&Medium=2&Model=Logistic+Prediction&NB=NB HTTP/1.1" 200 -
